---
title: "Human Factors in Job Accidents"
author: 
  - Dilek, Melike[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20450586, [Github Repo](https://github.com/MelikeDilek/Midterm.git/MelikeDilek/Midterm)

# Introduction
The pace of life is increasing day by day as a result of the rapid advancement of technology. As this fast pace shows itself also in business life, the importance of occupational safety has increased compared to previous periods. For more occupational safety, the factors that cause occupational accidents should be the subject of detailed research. These include economic, social, technological, and environmental factors. In this study, we analyzed workplace accidents with respetc to the way they occur and examined the personal factors that cause these accidents. We believe that the detailed analysis of these factors will make invaluable contributions to the knowledge of the measures that can be taken against occupational accidents. Research question: In which forms do occupational accidents occur most frequently and what are the personal factors that increase the risk of an accident?

## Literature Review
According to the results of four different academic researches whose findings we have examined, jobs that require long hours are riskier regardless of all other factors [@Dembe588 : 2005].Long working hours create fatigue that accumulates directly or indirectly in employees, and as a result, it causes an increase in work accidents. While the risk of work accidents is generally higher for men, long working hours increase the risk of work accidents for women, while this increase is not seen in men.[@ENACHE2013170 : 2013]In another study, researchers tried to find out whether there is a relationship between burnout syndrome and the way the person perceives himself, between the intensity of the burnout syndrome and work accidents, and between the burnout syndrome and their level of self-esteem [@https://doi.org/10.1111/j.1365-2869.1995.tb00220.x : 1995]. The results of the research have shown that workers who work long hours in a life full of economic uncertainties and who are burdened with workload and/or responsibilities more than they can bear experience fatigue and burnout syndrome, and as a result, they suffer more work accidents.Between 30% and 90% of severe occupational accidents in various sectors are due to fatigue. 68% of aviation accidents are caused by fatigue-related errors of either pilots or maintenance workers. Different studies have come to very different conclusions about whether this fatigue is due to sleep disorders, so we can say that this connection requires more research [@10.2307/41508902 :2012].


\newpage
# References {#references}
<div id="refs"></div>

